### ISSUE TITLE
Irrelevant Web Worker requests included

### ISSUE THREAD

**Issue by nattaylor** [machawk1/warcreate#119]
This "bug" seems to be a consequence of my browser environment, but I am observing a strange interaction with what I think are background Web Workers.  To recreate:

1) Open some web applications that use background web workers (Gmail, Google Drive, Google Calendar, open.spotify.com)
2) Open a simple page (https://nattaylor.com)
3) Create a WARC with the extension

At least in my case, the WARC contains a whole bunch of irrelevant requests that appear to be related to background web workers from the other tabs.  Take a look at [20191229150843960.warc.txt](https://github.com/machawk1/warcreate/files/4008191/20191229150843960.warc.txt)

Curiously, this is even true if I create the WARC in an incognito tab and have the other tabs in a normal tab.

Chrome: Version 79.0.3945.88 (Official Build) (64-bit)
MacOS: 10.15 (19A603)

**Comment by machawk1** [comment]
@nattaylor I am aware of this behavior and hope to fix it in #7. I am short on cycles at the moment but PRs welcome. I have put priority to #7, as it is a major issue. Thanks for the report.
